### ISSUE TITLE
Can't compare Bgra32 images

### ISSUE THREAD

**Issue by rhegner** [Codeuctivity/ImageSharp.Compare#101]
I'm trying out this library to compare a Bgra32 image with a reference image:

```
// loading the reference image as Bgra32
using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("PathToResource.png")!;
var referenceImage = Image.Load<Bgra32>(stream);

// comparing image under test:
var isEqual = ImageSharpCompare.ImagesAreEqual(imateToTest, referenceImage);
```

Both images should have the same pixel format, but this throws the following exception:
```
System.NotImplementedException: Pixel type SixLabors.ImageSharp.Formats.PixelTypeInfo is not supported to be compared.
         at Codeuctivity.ImageSharpCompare.ImageSharpCompare.ToRgb24Image(Image actual, Boolean& ownsImage)
         at Codeuctivity.ImageSharpCompare.ImageSharpCompare.ImagesAreEqual(Image actual, Image expected, ResizeOption resizeOption)
```

Is this a limitation of this library? Or is there anything I can do about it?

**Comment by stesee** [comment]
That is a (would be easy to solve) limitation of this library. For now only rgb is supported. Either convert your images to rgb before using this lib or even better:
Implement it in  Codeuctivity.ImageSharpCompare.ImageSharpCompare.ToRgb24Image an create a PR.

**Comment by stesee** [comment]
Bgra32 was added in https://github.com/Codeuctivity/ImageSharp.Compare/releases/tag/4.0.258 , please test.

**Comment by rhegner** [comment]
Sorry for the delayed response, I was on vacation.
Now it works fine! Thanks for the very quick update!
