### ISSUE TITLE
ImageSharpCompare.ImagesAreEqual: InnerException | {"Impossible de charger le fichier ou l'assembly 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0,

### ISSUE THREAD

**Issue by PatrickLeGarrec** [Codeuctivity/ImageSharp.Compare#27]
Codeuctivity.ImageSharpCompare 2.0.25

ImageSharpCompare.ImagesAreEqual: 

InnerException | {"Impossible de charger le fichier ou l'assembly 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou une de ses dépendances. La définition trouvée du manifeste de l'assembly ne correspond pas à la référence de l'assembly. (Exception de HRESULT : 0x80131040)":"System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"} | System.Exception {System.IO.FileLoadException}

**Comment by stesee** [comment]
Please check https://github.com/SixLabors/ImageSharp/issues/574 and if that does not help provide more information, like OS, .net Version, and some Code that causes your issue.
