### ISSUE TITLE
Requirement to see the differences between two images when a mask is used.

### ISSUE THREAD

**Issue by MJB222398** [Codeuctivity/ImageSharp.Compare#66]
For my application I am comparing two images using a mask image (ImageSharpCompare.CalcDiff) so that I can ignore differences between the two images in certain areas. In the case where a difference is found I want to be able to visualise that difference as it will be quite subtle and hard to spot without assistance. To do this the only method available is ImageSharpCompare.CalcDiffMaskImage but I cannot supply a mask to this. So what I get is an image representing the diff of the two images but it includes the areas that I expect to be different (the ones the mask would hide) and so it is difficult for me to see what the difference I did not expect actually is. 

I would like to be able to supply a filepath for an image mask when using the ImageSharpCompare.CalcDiffMaskImage method.

**Comment by stesee** [comment]
That's something we should add. I think a overload of ImageSharpCompare.CalcDiffMaskImage with an additional Parameter that takes an existing mask should cover this. What do you think?

**Comment by MJB222398** [comment]
Yes thats what I was envisioning. Hopefully a simple change and I imagine very useful for others too. We would need this for all the different methods that take the stream, filepath, image etc.

**Comment by MJB222398** [comment]
@stesee do you allow pull requests? I wanted to make one - on the Pull Requests tab I can see it says:

First time contributing to Codeuctivity/ImageSharp.Compare?
If you know how to fix an [issue](https://github.com/Codeuctivity/ImageSharp.Compare/issues), consider opening a pull request for it.

But if I try to push to a new branch it says permission denied.

**Comment by stesee** [comment]
Sure, that would be great.

**Comment by MJB222398** [comment]
Nice, but as I said above, its not possible I think. I appear not to have permission?

**Comment by stesee** [comment]
The common process for 1st time contributors is:

- Create a fork
- Change things in the fork
- Create a PR to the upstream project

**Comment by stesee** [comment]
good work. Please take a look at the review finding... public methods that were added should all have a test.

**Comment by MJB222398** [comment]
@stesee should be all done now

**Comment by MJB222398** [comment]
The advantages are fairly minor as far as I am aware, these being:

1. I would no longer have to keep syncing my fork in github. This caused me a spot of bother for this last bit of work where I pushed my commit locally to my remote fork without having synced it. I could not PR into your main repo until I had synced. But syncing meant that it removed my commit on my fork. When I then pulled my fork locally it removed my commit from my local repo. I got it back but scary moment. So its just that keeping up with changes is harder when using a fork.
2. I would have one fewer repo listed on my account - making it easier to find the repo I want.

These are minor things that I can definitely work with though so its fine if you prefer your current setup.

**Comment by MJB222398** [comment]
The only reason I had asked was that you'd said that using a fork was the process for 1st time contributors and as I had now made a couple of changes I thought there was already a mechanism in place to grant me the ability to work within this repo. Hadn't realised it was something that was not yet in place.

**Comment by stesee** [comment]
I apologize for the lack of clarity in my previous message. The concept I conveyed initially was meant to be interpreted flexibly. I genuinely value the notion of teamwork. I am in the process of scheduling time to adjust the security settings to accommodate contributors in future. 

Contributors do have potential access to the release build github action or deployment secrets. I need to verify these aspects before we can proceed.
