### ISSUE TITLE
New feature request: Color Difference Tolerance

### ISSUE THREAD

**Issue by huilaaja** [Codeuctivity/ImageSharp.Compare#90]
Hi, 
I'm comparing screenshots which contains really small pixel differences because of webp image compression creates a small variations between image generations.

I'm hoping to get additional parameter to CalcDiff and CalcDiffMaskImage methods (example int colorDiffTolerance = 0)
This tolerance (or threshold) value would remove all the errors when sum of all 3 colors difference would be lower than tolerance number.

It seems to be quite easy to implement.
Example 1. CalcDiff:
`pixelErrorCount += r + g + b > (colorDiffTolerance + 0) ? 1 : 0;`

Example 2. CalcDiffMaskImage:

```
var pixel = new Rgb24
{
    R = GetColorDiff(actualPixel.R, expectedPixel.R, colorDiffTolerance),
    G = GetColorDiff(actualPixel.G, expectedPixel.G, colorDiffTolerance),
    B = GetColorDiff(actualPixel.B, expectedPixel.B, colorDiffTolerance)
};

private static byte GetColorDiff(byte actualColor, byte expectedColor, int colorDiffTolerance)
{
    int diff = Math.Abs(actualColor - expectedColor);
    return (byte)(diff <= colorDiffTolerance ? 0 : diff);
}
```

P.s. Thank you for the great library.

**Comment by stesee** [comment]
Can you document/upload some example images that I can use in the tests?

**Comment by huilaaja** [comment]
Here is 2 small images where the compression seems to make really small difference and tollerance value would be handy.

![compare-2](https://github.com/Codeuctivity/ImageSharp.Compare/assets/2317542/efb77e68-a67f-44ee-859d-0fee03fdd626)
![compare-1](https://github.com/Codeuctivity/ImageSharp.Compare/assets/2317542/6baf75e9-b19e-438e-a580-d4da444bbdd6)

**Comment by stesee** [comment]
Give https://www.nuget.org/packages/Codeuctivity.ImageSharpCompare/4.0.228 a try and report. Please report if I missed something.

**Comment by huilaaja** [comment]
That's perfect! Thank you!
